version: 0.0
resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "<CONTAINER_NAME>"
          ContainerPort: <CONTAINER_PORT>
        PlatformVersion: "LATEST"
hooks:
  BeforeAllowTraffic:
    - location: before_allow_traffic.sh
      timeout: 600
      runas: root
      args:
        - 600
        

        
# This is sample file. AWS CodeBuild will generate and update all parameters when running
