version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in AWS ECR
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - echo Calculating image uri
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)_$(date +"%Y%m%d_%H%M%S")"

      - export IMAGE="${IMAGE_NAME}:$TAG"
      - export IMAGE_LATEST="${IMAGE_NAME}:latest"

      - echo -e "IMAGE=${IMAGE}\nIMAGE_LATEST=${IMAGE_LATEST}" > image_uri.txt
      - cat image_uri.txt

  build:
    commands:
      - echo "Building docker image"
      - docker build -f Dockerfile -t $IMAGE .
      - docker tag $IMAGE $IMAGE_LATEST

      - echo "Push $IMAGE to ECR"
      - docker push $IMAGE

      - echo "Push $IMAGE_LATEST to AWS ECR"
      - docker push $IMAGE_LATEST
  post_build:
    commands:
      - echo Logging out ECR
      - docker logout

artifacts:
  base-directory: .
  files:
    - image_uri.txt
